### ISSUE TITLE
ENZIP 8 - Capping Council Incentives

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/MIP#8]
ENZIP: 8
Title: Better incentive alignment at Council level
Author: Mona El Isa, Avantgarde
Status: Draft - not voted on
Type: ENZIP
Created: Feb 12th, 2021

### Abstract
ENZIP #8 attempts to describe a better incentive program at a governance level.

###Background
We feel that evenly distributing rewards amongst council members creates a free-rider problem for more passive members. More passive members risk disincentivizing higher contributors and performers on the Council. 
Furthermore, the steep appreciation in the MLN price in the last few months has made it difficult to justify the Council compensation which is currently 5454.5 MLN ($272k at $50/MLN) per year vested over 2 years. 

Because of the huge move in $MLN price, this is now equivalent to more than a full-time senior role, which is difficult to justify for all council members currently.

We think the governance process can be further improved by implementing a system which is more directly aligned with the actual work performed by the different Council members.

### Suggested Improvement 
At the start of each Enzyme year (March 1st), remuneration #MLN is calculated based on the lower of US$ 30,000 (equivalent in MLN) and (60,000 MLN divided by the # of Council members) in dollar terms per Council member. The MLN value for the former should be calculated using the 6mth rolling average.

This compensation is for following minimum requirements:
Attending a minimum of 75% of meetings per year (Meetings occur every two weeks)
Voting on at least 50% of all the votes in Aragon
Signing at least 50% of the multisig transactions
Prompt replies on the communications channel
At least 12 dedicated hours of contributions per year to at least one of the following working groups: tokenomics, protocol, grants, dev community & users

Tokens are distributed with interruptible vesting contracts over 2 yrs and contracts are revoked if the term is not complete

Members who perform extra (approved) hours of work within the council scope and beyond the minimum requirements can earn extra MLN (eg. audits, deploying contracts for the Council, legal work, community events, etc).  The amount in aggregate that can be earned by the Council is capped at 60,000 MLN in any one year.

### Implementation
Propose to implement this starting on March 1st 2021 with an honest and backward looking review to determine which members have got the drive, motivation and interest to continue. This will need a majority vote to pass.

**Comment by Deepcryptodive** [comment]
This has been voted on and approved in the Enzyme Council.

We all agree that current compensation is rather high, due to the MLN price appreciation the past year. 
Essentially, this ENZIP means cutting the minimal compensation by a factor of 7.5, to a yearly 725 MLN per Council Member (at the current MLN price levels). 

Any MLN tokens not used for compensation will also be burned at the end of the year. Similar to how unused developer grants are burned.
