### ISSUE TITLE
ENZIP 9: Piloting gas fee subsidization for trading on Enzyme 

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/MIP#9]
ENZIP: 9
Title: Piloting gas fee subsidization for trading on Enzyme #9
Author: Mona El Isa, Avantgarde
Status: Draft - discussed and verbally approved at last council meeting
Type: ENZIP
Created: Feb 22nd, 2021

**The Proposal**
Inspired by the recent gas subsidisation programs of Balancer and Paraswap, we've asked the Enzyme Council to consider launching a pilot for four weeks starting at 00:00 CET on Monday, March 1st, with possible extension. The Treasury would allocate up to 1,000 MLN for the month of March towards the partial reimbursement of gas costs for swaps performed through Paraswap through the Enzyme app.

**Motivation**
Whilst Enzyme v2 substantially reduced gas costs in many areas, the fact remains that trading costs are still high in the space. This may be holding back adoption. We are actively exploring L2 options and are confident these issues will be resolved medium term. However, until then, we have recently launched a new and much improved protocol and UI and we don’t want high gas prices to hinder the discovery and usage of v2, let alone all the new features we’ll be launching soon.

**Mechanics**
Swaps amounts equal to or higher than $250 (Max(sold Token, bought Token)) would be eligible to claim subsidies. 
Swaps must occur on Paraswap within the Enzyme app.
The 1,000 MLN will be distributed amongst all participants that comply with the participation rules. The percentage of the spent gas that you’ll get back on your Wallet can go up to 50% of the spent gas. However, no percentage is guaranteed since we can’t anticipate how many users will be eligible and how much gas fees they will accumulate.
Coingecko.com API will be used in order to determine the price. We’ll use a median daily price to simplify conversions.
Claiming $MLN will be possible at the end of the one month period . We’ll provide a simple UI for your to claim. You’ll have to sign a message with your wallet and we’ll send you the MLNs (to save you gas). This will work similarly to Paraswap’s recent farming program.
Only successful transactions will be reimbursable.
Reimbursements will be in $MLN.
It will be the Vault Managers and not the Vault themselves receiving any gas reimbursements.

**Comment by GMT-fintechv1** [comment]
Great move! What are the results of the pilot?
